config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  resources :sessions
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"

  get '/dragndrop', to: 'image#dragndrop'
  post '/dragndrop', to: 'image#upload_images'
  resources :image
  post '/upload_images', to: 'image#upload_images'
  resources :articles
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/articles/bm/:month', to: 'articles#by_month', as: 'articles_by_month'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: false
  validates_uniqueness_of :username
  has_many :articles

  validates :username, presence: {message: "não pode estar em branco."}, length: { in: 4..14, message: 'tem que ter entre 4 a 14 caracteres.' }, uniqueness: {message: 'já em uso.'}
  validates :email, presence: {message: "não pode estar em branco."}, uniqueness: {message: 'já em uso.'}
  validates :password, presence: {message: "não pode estar em branco."}, length: { in: 3..6, message: 'tem que ter entre 3 a 6 caracteres.' }

  HUMANIZED_ATTRIBUTES = {
  :email => "Email",
  :password => "Senha", # don't include column name in error
  :username => "Usuário"
  }

  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_timeout
  before_action :current_user

  def check_timeout
    timeout_period = 10.minutes
    if current_user && session[:last_request_at] && session[:last_request_at] < timeout_period.ago
      # current_user = nil
      # reset_session
      session[:user_id] = nil
      redirect_to new_session_path(previous_url: (root_url + request.path)), alert: "Sua sessão foi finalizada. Por favor faça login novamente."
    else
      session[:last_request_at] = Time.current
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: [:edit, :update]

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    page = params[:page] || 1
    @actual = page
    @per_page = 2
    offset = (page.to_i - 1) * @per_page
    @articles = Article.offset(offset).limit(@per_page).order(created_at: :desc)
    # @articles = Article.all.order(created_at: :desc)
  end


  def create
    @article = Article.create! params.require(:article).permit(:title, :user_id, :image, :content)
    @article.image.attach(params[:article][:image])
    # @article.content.attach(params[:article][:content])
      if @article.save
        return redirect_to article_path(@article.id)
      end
    render :new
    end

    def by_month
      date = Date.parse(params[:month])
      @articles = Article.where(created_at: date..date.end_of_month).order(created_at: :desc)
    end
    

  private
  def article_params
    params.require(:article).permit(:title, :user_id, :image, :content)
  end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  skip_before_action :verify_authenticity_token

  # In your controller
def upload_images
  images = params[:image]
    File.open(Rails.root.join("public/images", images.original_filename), "wb") do |file|
      file.write(images.read)
    end
    
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:alert] = "Logado com sucesso."
      if params[:from_url]
        redirect_to params[:from_url]
      else
        redirect_to root_url
      end
    else
      flash[:alert] = "Usuário ou senha inválidos."
      # render :new
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:alert] = "Sessão terminada com sucesso."
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Loga automaticamente o usuário
      session[:user_id] = @user.id
      flash[:notice] = "Logado com sucesso."
      redirect_to root_url
    else
      # render "new"
      render :new, status: :unprocessable_entity, content_type: "text/html"
    end
  end

  def index
    @users = User.all
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_right.html.erb
<div class="col-md-4">

  <div class="position-sticky" style="top:2rem;"

    <div class="p4 mb3 bg-light rounded" style="margin-bottom: 20px;">
      <h4 class="fst-italic">Artigos!</h4>
      <p class="mb-0">
      Aqui vai a descrição do site e etc, mas eu não quero escrever nada sério agora.
      </p>
    </div>
  
    <div class="p4 mb3 bg-light rounded" style="margin-bottom: 20px; margin-top: 20px;">
      <div class="card">
        <div class="card-header">
          Artigos por mês
          <ul class="list-group list-group-flush">
            <% @articles.group_by { |p| p.created_at.strftime("%B %Y") }.each do |month, articles| %>
            <li class="list-group-item"><%= link_to month, articles_by_month_path(month: month) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>


    <%= link_to "voltar", :back %>


    
  </div>
</div>

app/views/articles/by_month.html.erb
<div class="container">
<br />
<div style="text-align:center;"><h1>Artigos de <%= params[:month] %></h1></div>
<hr>
<br />

<% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <div><%= flash[:alert] %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>


  <div class="row g-5">
  <div class="col-md-8">

<% @articles.each_with_index do |a, idx| %>
  <% time = a.created_at.time.in_time_zone("Brasilia") %>
  <% n_time = time.strftime("%d/%m/%Y %H:%M") %>
 
      <div class="row g0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p3 d-flex flex-column position-static" style="margin: 10px;">
          <h2><%= link_to a.title, a, class: "article-title link-dark" %></h2>
          <i> Por <%= a.user.username %> - <%= n_time %> </i>
          <br />
          <i> Email <%= a.user.email %> </i>
          <br />
          <% rt_wo_attachments = a.content.body.to_plain_text %>
          <%= truncate(rt_wo_attachments, length: 300) %>
          <%= link_to 'Ver artigo', a %>
        </div>
        <div class="col-auto d-none d-lg-block" style="padding: 30px 0; margin-right: 10px;">
          <% images = a.content.body.attachments.select { |attachment| attachment} %>
          <% if images.count > 0 %>
            <% image = images[0] %>
              <%= image_tag image, alt: "Image Alt Text", size: "100", class: "resize rounded" %>
          <% end %>
        </div>
      </div>
    <% end %>

</div>

<%= render "right" %>

</div>


<br />
<br />

app/views/articles/index.html.erb
<% total_pages = (Article.count / @per_page) + (Article.count % @per_page) %>
<div class="container">
<br />
<div style="text-align:center;"><h1>Artigos</h1></div>
<hr>
<br />

<% if flash[:alert] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <div><%= flash[:alert] %></div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>


  <div class="row g-5">
  <div class="col-md-8">
<% @articles.each_with_index do |a, idx| %>
  <% time = a.created_at.time.in_time_zone("Brasilia") %>
  <% n_time = time.strftime("%d/%m/%Y %H:%M") %>
    <% if idx == 0 && @actual == 1 %>
      <div class="featured row g0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p3 d-flex flex-column position-static">
        <i>Em destaque</i>
          <div class="featured-title">
            <h2><%= a.title %></h2>
          </div>
          <i> Por <%= a.user.username %> - <%= n_time %> </i>
          <br />
          <i> Email <%= a.user.email %> </i>
          <br />
          <% rt_wo_attachments = a.content.body.to_plain_text %>
          <%= truncate(rt_wo_attachments, length: 300) %>
          <%= link_to 'Ver artigo', a %>
        </div>
        <div class="col-auto d-none d-lg-block" style="padding: 30px 0; margin-right: 10px;">
          <% images = a.content.body.attachments.select { |attachment| attachment} %>
          <% if images.count > 0 %>
            <% image = images[0] %>
              <%= image_tag image, alt: "Image Alt Text", size: "100", class: "resize rounded" %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="row g0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p3 d-flex flex-column position-static">
          <h2><%= link_to a.title, a, class: "article-title link-dark" %></h2>
          <i> Por <%= a.user.username %> - <%= n_time %> </i>
          <br />
          <i> Email <%= a.user.email %> </i>
          <br />
          <% rt_wo_attachments = a.content.body.to_plain_text %>
          <%= truncate(rt_wo_attachments, length: 300) %>
          <%= link_to 'Ver artigo', a %>
        </div>
        <div class="col-auto d-none d-lg-block" style="padding: 30px 0; margin-right: 10px;">
          <% images = a.content.body.attachments.select { |attachment| attachment} %>
          <% if images.count > 0 %>
            <% image = images[0] %>
              <%= image_tag image, alt: "Image Alt Text", size: "100", class: "resize rounded" %>
          <% end %>
        </div>
      </div>
    <% end %>
<% end %>
</div>


<%= render "right" %>

<% (1..total_pages).each do |page| %>
  <% if page == 1 %>
    <%= link_to page, root_path %>
  <% else %>
    <%= link_to page, root_path(page: page) %>
  <% end %>
<% end %>

</div>


<br />
<br />

app/views/articles/new.html.erb
<div class="around">
  <div class="internal">
  <h3>Novo artigo</h3>

  <div style="text-align: right;"><i class="bi bi-question-circle" id="toggle-link"></i></div>
  <div id="help" class="hidden" style="width: 800px;">
    <p>Primeiro preencha o título de seu artigo. O autor será atribuído automaticamente de acordo com seu usuário.</p>
    <p>No editor, os botões significam (da esquerda para a direita):</p>
    <p>Negrito - Itálico - Riscado - Link - Cabeçalho - Citação - Código - Lista - Lista numérica - 
    Diminuir nível - Aumentar nível - Anexar arquivo - Desfazer - Refazer</p>
    <p>Para inserir uma imagem você pode arrastá-la para dentro do editor.</p>

  </div>
  
    <dl>
    <%= form_with model: @article, local:true, method: "post", id: "myform" do |f| %>
      <dt>
        <%= f.text_field :title, placeholder: 'Título', class: "title-field" %>
      </dt>
      <dt>
      <br />
        <div style="width: 800px;">
          <% f.label :content %>
          <%= f.rich_text_area :content %>
        </div>
      </dt>
      <dt>
        <%= f.file_field :image, id: "input-field" %>
      </dt>
      <dt>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <br />
        <%= f.label 'Autor: ' + current_user.username %>
        <br />
        </dt>
      <dt>
        <%= f.submit "Post" %>
      </dt>
    <% end %>
    </dl>
  </div>
</div>

<script>
  const link = document.getElementById('toggle-link');
  const div = document.getElementById('help');
  link.addEventListener('click', () => {
    event.preventDefault();
    div.classList.toggle('hidden');
  });
</script>

app/views/articles/show.html.erb
<div class="container">
  <br /> 
  <% flash.each do |key, value| %>
    <div class="<%= key %> alert-warning" id="alert"><%= value %></div>
  <% end %>
  <div class="row g0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <div style="background-color: #212529; color:white; height: 100px; text-align: center; padding: 20px 0; margin-botton: 15px;">  
  <h1><%= @article.title %></h1>
  </div>
    <% time = @article.created_at.time.in_time_zone("Brasilia") %>
    <% n_time = time.strftime("%d/%m/%Y %H:%M") %>
  <div style="margin-top: 20px; margin-bottom: 20px;">
    <i>Por <%= @article.user.username %>, <%= @article.user.email %> - <%= n_time %></i>
  </div>
    <div class="out">
      <div>
        
      </div>
      
      <div class="image">
        <% if @article.image.present? %>
          <img src="<%= (url_for(@article.image)) %>">
        <% end %>
      </div>
      <%= @article.content %>
    </div>

    <br />
    <br />
    <%= link_to "Voltar", :back %>
    <br />
    <br />
  </div>
</div>

app/views/image/dragndrop.html.erb
<div id="dropzone" ondragover="allowDrop(event)">
    Drop your image here
  </div>
<%= form_with(model: @image, local: true, html: { id: "myform", style: "display:none" }) do |form| %>
  
  <%= form.file_field :image, id: "input-field" %>
  <%= form.submit "Submit" %>
<% end %>

<script>
function allowDrop(event) {
  event.preventDefault();
}
  const dropzone = document.getElementById("dropzone");
  const myform = document.getElementById("myform");
  dropzone.addEventListener("drop", (event) => {
    event.preventDefault();
    const file = event.dataTransfer.files;
    const input = document.getElementById("input-field");
    input.files = file;
    myform.submit();
    
  const file2 = event.dataTransfer.files[0];
  const reader = new FileReader();
  reader.readAsDataURL(file2);
  reader.onload = function() {
    const dataUrl = reader.result;
    const img = document.createElement('img');
    img.src = dataUrl;
    dropzone.appendChild(img);
    }
  });
</script>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Images</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  <nav class="navbar navbar-expand-lg" style="background-color: #90a1b3;">
    <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <span class="navbar-brand"> Artigos! </span>
        <li class="nav-item">
            <%= link_to "Artigos", root_path, class: "nav-link" %>
        </li>
        <% if current_user %>
          <li class="nav-item">  
            <%= link_to "Novo artigo", new_article_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if current_user %>
          <span class="navbar-text"> Logado como <%= current_user.username %>.</span>
          <li class="nav-item">
            <%= link_to "Sair", logout_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Inscrição", signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Entrar", login_path(previous_url: (root_url + request.path)), class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h1>Inscrição</h1>


  <% if flash[:alert] %>
    <div class="alert alert-warning">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <% if flash[:danger] %>
    <script>
      window.confirm("<%= flash[:danger] %>");
    </script>
  <% end %>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "Nome de usuário" %><br />
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label "Email" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label "Senha" %><br />
      <%= f.password_field :password, id: "password" %>
    </div>
    <div class="field">
      <%= f.label "Confirmação da senha" %><br />
      <%= f.password_field :password_confirmation, id: "password_confirmation" %>
    </div>
    <div class="actions"><%= f.submit "Sign Up", id: "submit" %></div>
  <% end %>
  <br />
  <%= link_to "Voltar", :back %>
</div>

<script>
  document.querySelector("#submit").addEventListener("click", function(event) {
    var password = document.querySelector("#password");
    var retypePassword = document.querySelector("#password_confirmation");
    if (password.value !== retypePassword.value) {
      event.preventDefault();
      password.classList.add("error");
      retypePassword.classList.add("error");
      alert("As senhas não são iguais. Tente novamente.");
    }
  });
</script>